### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by jeremypmoss** [rfrazier716/PyRayT#4]
TypeError                                 Traceback (most recent call last)
C:\Users\JEREMY~1\AppData\Local\Temp/ipykernel_27444/104715509.py in <module>
      1 # https://pyrayt.readthedocs.io/en/latest/tutorial.html
----> 2 import pyrayt

~\anaconda3\lib\site-packages\pyrayt\__init__.py in <module>
      3 from ._pyrayt import *
      4 
----> 5 from . import materials
      6 from . import components

~\anaconda3\lib\site-packages\pyrayt\materials.py in <module>
     63 
     64 
---> 65 class Glass(TracableMaterial):
     66     def __init__(self, *args, **kwargs):
     67         """Abstract base class for glasses with convenience functions for common parameters."""

~\anaconda3\lib\site-packages\pyrayt\materials.py in Glass()
     76 
     77     @lru_cache
---> 78     def abbe(self) -> float:
     79         """
     80         Calculates the `Abbe number <https://en.wikipedia.org/wiki/Abbe_number>`_ of the material.

~\anaconda3\lib\functools.py in lru_cache(maxsize, typed)
    488             maxsize = 0
    489     elif maxsize is not None:
--> 490         raise TypeError('Expected maxsize to be an integer or None')
    491 
    492     def decorating_function(user_function):

TypeError: Expected maxsize to be an integer or None

**Comment by rfrazier716** [comment]
Hi Jeremy,

Can you let me know your python version and how you're installing PyRayT? I tried replicating the error in a clean Anaconda environment but the library loads without issue.

```sh
(test_env) ryan@fotonix-ubuntu:~/anaconda3/bin$ py
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrayt
>>> 
```

**Comment by jeremypmoss** [comment]
First tried loading into a jupyter notebook, then into Anaconda. Same error
occurs:

Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
> Type "copyright", "credits" or "license" for more information.
>
> IPython 7.26.0 -- An enhanced Interactive Python.
>
> import pyrayt
> Traceback (most recent call last):
>
>   File
> "C:\Users\JEREMY~1\AppData\Local\Temp/ipykernel_27508/112383670.py", line
> 1, in <module>
>     import pyrayt
>
>   File "C:\Users\Jeremy
> Moss\anaconda3\lib\site-packages\pyrayt\__init__.py", line 5, in <module>
>     from . import materials
>
>   File "C:\Users\Jeremy
> Moss\anaconda3\lib\site-packages\pyrayt\materials.py", line 65, in <module>
>     class Glass(TracableMaterial):
>
>   File "C:\Users\Jeremy
> Moss\anaconda3\lib\site-packages\pyrayt\materials.py", line 78, in Glass
>     def abbe(self) -> float:
>
>   File "C:\Users\Jeremy Moss\anaconda3\lib\functools.py", line 490, in
> lru_cache
>     raise TypeError('Expected maxsize to be an integer or None')
>
> TypeError: Expected maxsize to be an integer or None

_______________________________
Jeremy (Jim) Moss
https://jeremypmoss.wixsite.com/jeremypmoss

**Comment by rfrazier716** [comment]
Thanks Jim,

looks like this is an issue with python 3.7's `lru_cache`, in 3.8+ it can decorate without arguments but 3.7 needs the cache size explicitly mentioned. I'll fix this in the next few days and make sure there aren't any more gotchas with 3.7.

In the mean time if you have python 3.8+ installed it should install and run without a hitch.

**Comment by rfrazier716** [comment]
v0.3.1 should fix this, you can update to it with:

```sh
py -m pip install --upgrade pyrayt
```

Thanks for checking out the project!
